## Exercici 1

*__Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.__*

In [6]:
import numpy as np

def resum(arr):
    if arr.ndim == 1:
        return True
    else:
        return False

arr = np.array([0, 1, 2, 3, 4, 5])

if resum(arr):
    print("La suma de tots els elements és", np.sum(arr))
    print("El valor mínim és:", np.min(arr))
    print("El valor màxim és:", np.max(arr, axis=0))
    print("La suma acumulativa és:", np.cumsum(arr, axis=0))
    print("El valor mig és:", np.mean(arr))
    print("La mitjana és:", np.median(arr))
    print("El coeficient de correlació és:", np.corrcoef(arr))
else:
    print("ERROR, aquesta array te més d'una dimensió")

La suma de tots els elements és 15
El valor mínim és: 0
El valor màxim és: 5
La suma acumulativa és: [ 0  1  3  6 10 15]
El valor mig és: 2.5
La mitjana és: 2.5
El coeficient de correlació és: 1.0


## Exercici 2

*__Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.__*

In [9]:
from numpy import random
def quadrat(a):
    x = random.randint(100, size=(a, a))
    print(x)

quadrat(3)

[[ 6 17 74]
 [34 68 95]
 [68  1 95]]


## Exercici 3

*__Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.__*

In [22]:
def funcio(arr):
    print("La suma total de les columnes és el següent:", np.sum(arr, axis=0))
    print("La suma total de les files és el següent:", np.sum(arr, axis=1))
    
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
funcio(arr)

2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
La suma total de les columnes és el següent: [12 15 18]
La suma total de les files és el següent: [ 6 15 24]


## Exercici 4

*__Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.__*

In [ ]:
'''
La fórmula del coeficiente de correlación es la siguiente:
r = Oxy/(Ox*Oy) 
Donde:
r = coeficiente de correlación
Oxy = covarianza = ((Suma de xy)/n(numero de muestras)) - Xm * Ym (medias de X y Y)
Ox = desviación típica de x = Raiz cuadrada de la (suma de x^2/n) - Xm
Oy = desviación típica de x = Raiz cuadrada de la (suma de y^2/n) - Xy



In [6]:
import numpy as np
def coef_corr(arr1, arr2):
    n = len(arr1)
    arr1_media = np.mean(arr1)
    arr2_media = np.mean(arr2)
    arr_multiplicación_suma = np.sum(arr1*arr2)
    
    covarianza = (arr_multiplicación_suma/n) - (arr1_media * arr2_media)
    desviación_arr1 = (((np.sum(arr1**2)/n) - arr1_media**2)**0.5)
    desviación_arr2 = (((np.sum(arr2**2)/n) - arr2_media**2)**0.5)
    
    return covarianza/(desviación_arr1*desviación_arr2)

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 5, 6, 8])

print(coef_corr(arr1, arr2))
print(np.corrcoef(arr1, arr2)[0, 1]) #també pot ser [1, 0] -> comprobació

0.9922778767136677
0.9922778767136676


In [ ]:
'''
La correlación trata de establecer la relación o dependencia que existe entre las dos variables que intervienen 
en una distribución bidimensional. Es decir, determinar si los cambios en una de las variables influyen en los cambios de la 
otra. En caso de que suceda, diremos que las variables están correlacionadas o que hay correlación entre ellas. 
La correlación es positiva cuando los valores de las variables aumenta juntos; y es negativa cuando un valor de una variable 
se reduce cuando el valor de la otra variable aumenta.
'''

